<?php

namespace App\Database\Seeds;

use CodeIgniter\I18n\Time;
use CodeIgniter\Database\Seeder;

class DSProdukSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-01-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-01-02.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-01-03.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-02-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-02-02.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-02-03.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-03-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-03-02.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-03-03.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "04",
                "image" => "butto-pants-01-03-sc01-03-04.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => 160650,
                "percent_disc" => 15,
                "discount" => 1,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc06",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "chino-pants-02-03-sc06-01-02.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc06",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "chino-pants-02-03-sc06-01-03.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc06",
                "color_id" => "12",
                "size_id" => "03",
                "image" => "chino-pants-02-03-sc06-12-03.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc06",
                "color_id" => "12",
                "size_id" => "02",
                "image" => "chino-pants-02-03-sc06-12-02.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc07",
                "color_id" => "01",
                "size_id" => "04",
                "image" => "dean-culotte-03-03-sc07-01-02.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc07",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "dean-culotte-03-03-sc07-01-03.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc07",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "dean-culotte-03-03-sc07-05-03.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc07",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "dean-culotte-03-03-sc07-05-02.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "01",
                "size_id" => "04",
                "image" => "flare-pants-04-03-sc08-01-04.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "flare-pants-04-03-sc08-01-02.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "flare-pants-04-03-sc08-01-03.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "flare-pants-04-03-sc08-05-01.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "flare-pants-04-03-sc08-05-02.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc08",
                "color_id" => "05",
                "size_id" => "03",
                "image" => "flare-pants-04-03-sc08-05-03.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "01",
                "size_id" => "04",
                "image" => "gemma-pants-05-03-sc09-01-04.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "gemma-pants-05-03-sc09-01-02.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "gemma-pants-05-03-sc09-01-03.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "gemma-pants-05-03-sc09-05-01.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "gemma-pants-05-03-sc09-05-02.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc09",
                "color_id" => "05",
                "size_id" => "03",
                "image" => "gemma-pants-05-03-sc09-05-0.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-04-01.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-04-02.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-04-03.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-05-01.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-05-02.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-05-03.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "04",
                "image" => "ali-seris-01-02-sc02-05-04.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-01-01.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-01-02.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => 143100,
                "percent_disc" => 10,
                "discount" => 1,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-01-03.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "bukhori-seris-02-02-sc02-01-01.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "bukhori-seris-02-02-sc02-01-02.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "bukhori-seris-02-02-sc02-01-03.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "05",
                "size_id" => "04",
                "image" => "bukhori-seris-02-02-sc02-05-04.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "05",
                "size_id" => "05",
                "image" => "bukhori-seris-02-02-sc02-05-05.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc10",
                "color_id" => "05",
                "size_id" => "06",
                "image" => "bukhori-seris-02-02-sc02-05-06.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "15",
                "size_id" => "01",
                "image" => "thobe-premium-01-01-sc03-15-01.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "15",
                "size_id" => "02",
                "image" => "thobe-premium-01-01-sc03-15-02.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "15",
                "size_id" => "03",
                "image" => "thobe-premium-01-01-sc03-15-03.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "12",
                "size_id" => "04",
                "image" => "thobe-premium-01-01-sc03-12-04.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "12",
                "size_id" => "05",
                "image" => "thobe-premium-01-01-sc03-12-05.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "12",
                "size_id" => "06",
                "image" => "thobe-premium-01-01-sc03-12-06.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "05",
                "size_id" => "07",
                "image" => "thobe-premium-01-01-sc03-05-07.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "thobe-premium-01-01-sc03-05-01.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "thobe-premium-01-01-sc03-05-02.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "salman-seris-02-01-sc05-01-01.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "salman-seris-02-01-sc05-01-02.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "salman-seris-02-01-sc05-01-03.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "salman-seris-02-01-sc05-05-01.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "05",
                "size_id" => "05",
                "image" => "salman-seris-02-01-sc05-05-05.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "05",
                "size_id" => "03",
                "image" => "salman-seris-02-01-sc05-05-03.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "15",
                "size_id" => "04",
                "image" => "salman-seris-02-01-sc05-15-04.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "15",
                "size_id" => "05",
                "image" => "salman-seris-02-01-sc05-15-05.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc05",
                "color_id" => "15",
                "size_id" => "07",
                "image" => "salman-seris-02-01-sc05-15-07.jpg",
                "price" => 180000,
                "weight" => 3000,
                "stock" => 44,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "cardinal-cj-06-02-sc04-01-03.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 90,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "cardinal-cj-06-02-sc04-01-02.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 88,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "cardinal-cj-06-02-sc04-01-01.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 99,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "01",
                "image" => "cardinal-cj-06-02-sc04-02-01.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 78,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "cardinal-cj-06-02-sc04-05-02.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 55,
                "price_disc" => 260100,
                "percent_disc" => 10,
                "discount" => 1,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "05",
                "image" => "cardinal-cj-06-02-sc04-02-05.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 56,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "02",
                "image" => "cardinal-cj-06-02-sc04-02-02.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 55,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "created_at" => TIme::now()
            ]
        ];

        // Using Query Builder
        $this->db->table('ds_product')->insertBatch($data);
    }
}
