<?php

namespace App\Database\Seeds;

use CodeIgniter\I18n\Time;
use CodeIgniter\Database\Seeder;

class DSProdukSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-01-01.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-01-02.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-01-03.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-02-01.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-02-02.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "02",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-02-03.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "01",
                "image" => "butto-pants-01-03-sc01-03-01.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "02",
                "image" => "butto-pants-01-03-sc01-03-02.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "03",
                "image" => "butto-pants-01-03-sc01-03-03.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc01",
                "color_id" => "03",
                "size_id" => "04",
                "image" => "butto-pants-01-03-sc01-03-04.jpg",
                "price" => 189000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-04-01.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-04-02.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "04",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-04-03.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-05-01.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-05-02.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-05-03.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "05",
                "size_id" => "04",
                "image" => "ali-seris-01-02-sc02-05-04.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "06",
                "size_id" => "01",
                "image" => "ali-seris-01-02-sc02-06-01.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "06",
                "size_id" => "02",
                "image" => "ali-seris-01-02-sc02-06-02.jpg",
                "price" => 159000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc02",
                "color_id" => "06",
                "size_id" => "03",
                "image" => "ali-seris-01-02-sc02-06-03.jpg",
                "price" => 159000,
                "price_disc" => 143100,
                "percent_disc" => 10,
                "discount" => 1,
                "weight" => 3500,
                "stock" => 50,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "07",
                "size_id" => "01",
                "image" => "thobe-premium-01-01-sc03-07-01.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "07",
                "size_id" => "02",
                "image" => "thobe-premium-01-01-sc03-07-02.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "07",
                "size_id" => "03",
                "image" => "thobe-premium-01-01-sc03-07-03.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "07",
                "size_id" => "04",
                "image" => "thobe-premium-01-01-sc03-07-04.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "08",
                "size_id" => "01",
                "image" => "thobe-premium-01-01-sc03-08-01.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "08",
                "size_id" => "02",
                "image" => "thobe-premium-01-01-sc03-08-02.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "08",
                "size_id" => "03",
                "image" => "thobe-premium-01-01-sc03-08-03.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "09",
                "size_id" => "01",
                "image" => "thobe-premium-01-01-sc03-09-01.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "09",
                "size_id" => "02",
                "image" => "thobe-premium-01-01-sc03-09-02.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc03",
                "color_id" => "09",
                "size_id" => "03",
                "image" => "thobe-premium-01-01-sc03-09-03.jpg",
                "price" => 289000,
                "price_disc" => 260100,
                "percent_disc" => 10,
                "discount" => 1,
                "weight" => 5000,
                "stock" => 100,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "03",
                "image" => "cardinal-cj-06-02-sc04-01-03.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 90,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "02",
                "image" => "cardinal-cj-06-02-sc04-01-02.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 88,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "01",
                "size_id" => "01",
                "image" => "cardinal-cj-06-02-sc04-01-01.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 99,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "01",
                "image" => "cardinal-cj-06-02-sc04-02-01.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 78,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "02",
                "image" => "cardinal-cj-06-02-sc04-02-02.jpg",
                "price" => 289000,
                "price_disc" => 260100,
                "percent_disc" => 10,
                "discount" => 1,
                "weight" => 5000,
                "stock" => 55,
                "created_at" => TIme::now()
            ],
            [
                "sub_code" => "sc04",
                "color_id" => "02",
                "size_id" => "05",
                "image" => "cardinal-cj-06-02-sc04-02-05.jpg",
                "price" => 289000,
                "price_disc" => null,
                "percent_disc" => null,
                "discount" => null,
                "weight" => 5000,
                "stock" => 56,
                "created_at" => TIme::now()
            ]
        ];

        // Using Query Builder
        $this->db->table('ds_product')->insertBatch($data);
    }
}
