<?php

namespace App\Database\Seeds;

use CodeIgniter\I18n\Time;
use CodeIgniter\Database\Seeder;

class MProductSeeds extends Seeder
{
    public function run()
    {
        $data = [
            [
                "name" => "BUTTON PANTS",
                "slug" => "butto-pants-01",
                "product_id" => "01",
                "category_id" => "03",
                "color_id" => "10",
                "size_id" => "01",
                "description" => "",
                "image" => "butto-pants-01-03-10-01.jpg",
                "price" => "189000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "CHINO PANTS",
                "slug" => "chino-pants-02",
                "product_id" => "02",
                "category_id" => "03",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "chino-pants-02-03-06-01.jpg",
                "price" => "199000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "DEAN CULOTTE",
                "slug" => "dean-culotte-03",
                "product_id" => "03",
                "category_id" => "03",
                "color_id" => "11",
                "size_id" => "01",
                "description" => "",
                "image" => "dean-culotte-03-03-11-01.jpg",
                "price" => "189000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "FLARE PANTS",
                "slug" => "flare-pants-04",
                "product_id" => "04",
                "category_id" => "03",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "flare-pants-04-03-12-01.jpg",
                "price" => "179000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "GEMMA PANTS",
                "slug" => "gemma-pants-05",
                "product_id" => "05",
                "category_id" => "03",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "gemma-pants-05-03-09-01.jpg",
                "price" => "179000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "INNER PENTS",
                "slug" => "inner-pents-06",
                "product_id" => "06",
                "category_id" => "03",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "inner-pents-06-03-09-01.jpg",
                "price" => "89000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIGH WAIST CULOTTE",
                "slug" => "high-waist-culotte-07",
                "product_id" => "07",
                "category_id" => "03",
                "color_id" => "10",
                "size_id" => "01",
                "description" => "",
                "image" => "high-waist-culotte-07-03-10-01.jpg",
                "price" => "189000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "KNIT JOGGER PANTS",
                "slug" => "knit-jogger-pants-08",
                "product_id" => "08",
                "category_id" => "03",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "knit-jogger-pants-08-03-04-01.jpg",
                "price" => "199000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "LINEA PANTS",
                "slug" => "linea-pants-09",
                "product_id" => "09",
                "category_id" => "03",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "linea-pants-09-03-04-01.jpg",
                "price" => "189000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "WIDE PANTS",
                "slug" => "wide-pants-10",
                "product_id" => "10",
                "category_id" => "03",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "wide-pants-10-03-12-01.jpg",
                "price" => "199000",
                "weight" => "3000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ALI SERIS",
                "slug" => "ali-seris-01",
                "product_id" => "01",
                "category_id" => "02",
                "color_id" => "13",
                "size_id" => "01",
                "description" => "‼️OPEN PRE ORDER 22-24 JUNI 2022‼️ Pengen pake kemeja tapi tetep keliatan fresh? Atau.. mau beli kemeja tapi takut gak dipake karna biasanya bahannya gak nyaman, gerah, kasar, dan kaku? Tenang aja kang bro, kan sekarang ada Ali Series by Muslim Basic😎 Solusi buat kang bro yang mau pake kemeja tapi masih tetep mau keliatan CASUAL, RAPIH dan NYAMAN. Tentunya bisa dipake di segala aktivitas Insyā Allāh👍🏻",
                "image" => "ali-seris-01-02-13-01.jpg",
                "price" => "159000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "BUKHORI SERIS",
                "slug" => "bukhori-seris-02",
                "product_id" => "02",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "bukhori-seris-02-02-05-01.jpg",
                "price" => "150000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ANDREW SMITH LENGAN PANJANG ",
                "slug" => "andrew-smith-lengan-panjang-03",
                "product_id" => "03",
                "category_id" => "02",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-lengan-panjang-03-02-09-01.jpg",
                "price" => "200000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ANDREW SMITH LENGAN PENDEK ",
                "slug" => "andrew-smith-lengan-pendek-04",
                "product_id" => "04",
                "category_id" => "02",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-lengan-pendek -04-02-12-01.jpg",
                "price" => "180000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "CARDINAL JEANS",
                "slug" => "cardinal-jeans-05",
                "product_id" => "05",
                "category_id" => "02",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-jeans-05-02-12-01.jpg",
                "price" => "200000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "CARDINAL CJ",
                "slug" => "cardinal-cj-06",
                "product_id" => "06",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-cj-06-02-05-01.jpg",
                "price" => "200000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "CARDINAL KEMEJA",
                "slug" => "cardinal-kemeja-07",
                "product_id" => "07",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-kemeja-07-02-05-01.jpg",
                "price" => "200000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "CARDINAL  CCSL",
                "slug" => "cardinal-ccsl-08",
                "product_id" => "08",
                "category_id" => "02",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-ccsl-08-02-12-01.jpg",
                "price" => "210000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ANDREW SMITH KEMEJA",
                "slug" => "andrew-smith-kemeja-09",
                "product_id" => "09",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-kemeja-09-02-05-01.jpg",
                "price" => "210000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ANDREW SMITH",
                "slug" => "andrew-smith-10",
                "product_id" => "10",
                "category_id" => "02",
                "color_id" => "14",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-10-02-14-01.jpg",
                "price" => "200000",
                "weight" => "3500",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "THOBE PREMIUM",
                "slug" => "thobe-premium-01",
                "product_id" => "01",
                "category_id" => "01",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "thobe-premium-01-01-04-01.jpg",
                "price" => "289000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "SALMAN SERIS",
                "slug" => "salman-seris-02",
                "product_id" => "02",
                "category_id" => "01",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "‼️OPEN PRE ORDER 11-15 JULI 2022‼️ Pengen gamisan tapi takut keliatan terlalu formal? Atau.. mau beli gamis tapi takut cuma ngegantung di lemari aja karena gamis identiknya cuma dipake pas jum’atan aja? Tenang aja kang bro, kan ada Salman Series by Muslim Basic😎 Solusi buat kang bro yang mau pake gamis tapi masih tetep mau keliatan CASUAL dan NYAMAN. Tentunya bisa dipake di segala aktivitas Insyā Allāh👍🏻",
                "image" => "salman-seris-02-01-01-01.jpg",
                "price" => "200000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "THOBE SACHET",
                "slug" => "thobe-sachet-03",
                "product_id" => "03",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "!!OPEN PRE ORDER 26-29 JULI 2022!!Mau pakai thobe premium, tapi biasanya harganya mahal?Tenang aja kang bro, kan ada Adam series by Muslim Basic. Muslim Basic bi'idznillah hadir untuk memfasilitasi kang bro semua supaya bisa TETAP TAAT dan MENAWAN tapi gak bikin kantong jebol",
                "image" => "thobe-sachet-03-01-05-01.jpg",
                "price" => "250000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "NOOR ABAY",
                "slug" => "noor-abay-04",
                "product_id" => "04",
                "category_id" => "01",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "noor-abay-04-01-01-01.jpg",
                "price" => "160000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "BALQIS ABAYA",
                "slug" => "balqis-abaya-05",
                "product_id" => "05",
                "category_id" => "01",
                "color_id" => "03",
                "size_id" => "01",
                "description" => "",
                "image" => "balqis-abaya-05-01-03-01.jpg",
                "price" => "160000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "NONA ABAYA",
                "slug" => "nona-abaya-06",
                "product_id" => "06",
                "category_id" => "01",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "nona-abaya-06-01-09-01.jpg",
                "price" => "160000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "JOBB",
                "slug" => "jobb-07",
                "product_id" => "07",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "jobb-07-01-05-01.jpg",
                "price" => "200000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "SALT N PEPPER",
                "slug" => "salt-n-pepper-08",
                "product_id" => "08",
                "category_id" => "01",
                "color_id" => "12",
                "size_id" => "01",
                "description" => "",
                "image" => "salt-n-pepper-08-01-12-01.jpg",
                "price" => "200000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "ARJUNA WEDA",
                "slug" => "arjuna-weda-09",
                "product_id" => "09",
                "category_id" => "01",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "arjuna-weda-09-01-06-01.jpg",
                "price" => "200000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "LOIS JEANS",
                "slug" => "lois-jeans-10",
                "product_id" => "10",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "lois-jeans-10-01-05-01.jpg",
                "price" => "250000",
                "weight" => "5000",
                "stock" => "100",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris-01",
                "product_id" => "01",
                "category_id" => "04",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-01-04-01-01.jpg",
                "price" => "160000",
                "weight" => "4000",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris-02",
                "product_id" => "02",
                "category_id" => "04",
                "color_id" => "07",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-02-04-07-01.jpg",
                "price" => "175000",
                "weight" => "4000",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris-03",
                "product_id" => "03",
                "category_id" => "04",
                "color_id" => "08",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-03-04-08-01.jpg",
                "price" => "160000",
                "weight" => "4000",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris-04",
                "product_id" => "04",
                "category_id" => "04",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-04-04-01-01.jpg",
                "price" => "160000",
                "weight" => "4000",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris-05",
                "product_id" => "05",
                "category_id" => "04",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-05-04-06-01.jpg",
                "price" => "160000",
                "weight" => "4000",
                "stock" => "50",
                "is_valid" => "1",
                "created_at" => Time::now()
            ]
        ];

        // Using Query Builder
        $this->db->table('m_product')->insertBatch($data);
    }
}
