<?php

namespace App\Database\Seeds;

use CodeIgniter\I18n\Time;
use CodeIgniter\Database\Seeder;

class MProductSeeds extends Seeder
{
    public function run()
    {
        $data = [
            [
                "name" => "BUTTON PANTS",
                "slug" => "butto- pants",
                "product_id" => "01",
                "category_id" => "03",
                "color_id" => "010",
                "size_id" => "01",
                "description" => "",
                "image" => "butto- pants-01-03-010-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "CHINO PANTS",
                "slug" => "chino-pants",
                "product_id" => "02",
                "category_id" => "03",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "chino-pants-02-03-06-01.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "DEAN CULOTTE",
                "slug" => "dean-culotte",
                "product_id" => "03",
                "category_id" => "03",
                "color_id" => "011",
                "size_id" => "01",
                "description" => "",
                "image" => "dean-culotte-03-03-011-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "FLARE PANTS",
                "slug" => "flare-pants",
                "product_id" => "04",
                "category_id" => "03",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "flare-pants-04-03-012-01.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "GEMMA PANTS",
                "slug" => "gemma-pants",
                "product_id" => "05",
                "category_id" => "03",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "gemma-pants-05-03-09-01.jpg",
                "price" => 179000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "INNER PENTS",
                "slug" => "inner-pents",
                "product_id" => "06",
                "category_id" => "03",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "inner-pents-06-03-09-01.jpg",
                "price" => 89000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIGH WAIST CULOTTE",
                "slug" => "high-waist-culotte",
                "product_id" => "07",
                "category_id" => "03",
                "color_id" => "010",
                "size_id" => "01",
                "description" => "",
                "image" => "high-waist-culotte-07-03-010-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "KNIT JOGGER PANTS",
                "slug" => "knit-jogger-pants",
                "product_id" => "08",
                "category_id" => "03",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "knit-jogger-pants-08-03-04-01.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "LINEA PANTS",
                "slug" => "linea-pants",
                "product_id" => "09",
                "category_id" => "03",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "linea-pants-09-03-04-01.jpg",
                "price" => 189000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "WIDE PANTS",
                "slug" => "wide-pants",
                "product_id" => "10",
                "category_id" => "03",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "wide-pants-10-03-012-01.jpg",
                "price" => 199000,
                "weight" => 3000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ALI SERIS",
                "slug" => "ali-seris",
                "product_id" => "01",
                "category_id" => "02",
                "color_id" => "013",
                "size_id" => "01",
                "description" => "‼️OPEN PRE ORDER 22-24 JUNI 2022‼️ Pengen pake kemeja tapi tetep keliatan fresh? Atau.. mau beli kemeja tapi takut gak dipake karna biasanya bahannya gak nyaman, gerah, kasar, dan kaku? Tenang aja kang bro, kan sekarang ada Ali Series by Muslim Basic😎 Solusi buat kang bro yang mau pake kemeja tapi masih tetep mau keliatan CASUAL, RAPIH dan NYAMAN. Tentunya bisa dipake di segala aktivitas Insyā Allāh👍🏻",
                "image" => "ali-seris-01-02-013-01.jpg",
                "price" => 159000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "BUKHORI SERIS",
                "slug" => "bukhori-seris",
                "product_id" => "02",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "bukhori-seris-02-02-05-01.jpg",
                "price" => 150000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ANDREW SMITH LENGAN PANJANG ",
                "slug" => "andrew-smith-lengan-panjang ",
                "product_id" => "03",
                "category_id" => "02",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-lengan-panjang -03-02-09-01.jpg",
                "price" => 200000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ANDREW SMITH LENGAN PENDEK ",
                "slug" => "andrew-smith-lengan-pendek ",
                "product_id" => "04",
                "category_id" => "02",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-lengan-pendek -04-02-012-01.jpg",
                "price" => 180000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "CARDINAL JEANS",
                "slug" => "cardinal-jeans",
                "product_id" => "05",
                "category_id" => "02",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-jeans-05-02-012-01.jpg",
                "price" => 200000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "CARDINAL CJ",
                "slug" => "cardinal-cj",
                "product_id" => "06",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-cj-06-02-05-01.jpg",
                "price" => 200000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "CARDINAL KEMEJA",
                "slug" => "cardinal-kemeja",
                "product_id" => "07",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal-kemeja-07-02-05-01.jpg",
                "price" => 200000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "CARDINAL  CCSL",
                "slug" => "cardinal -ccsl",
                "product_id" => "08",
                "category_id" => "02",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "cardinal -ccsl-08-02-012-01.jpg",
                "price" => 210000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ANDREW SMITH KEMEJA",
                "slug" => "andrew-smith-kemeja",
                "product_id" => "09",
                "category_id" => "02",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-kemeja-09-02-05-01.jpg",
                "price" => 210000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ANDREW SMITH",
                "slug" => "andrew-smith",
                "product_id" => "10",
                "category_id" => "02",
                "color_id" => "014",
                "size_id" => "01",
                "description" => "",
                "image" => "andrew-smith-10-02-014-01.jpg",
                "price" => 200000,
                "weight" => 3500,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "THOBE PREMIUM",
                "slug" => "thobe-premium",
                "product_id" => "01",
                "category_id" => "01",
                "color_id" => "04",
                "size_id" => "01",
                "description" => "",
                "image" => "thobe-premium-01-01-04-01.jpg",
                "price" => 289000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "SALMAN SERIS",
                "slug" => "salman-seris",
                "product_id" => "02",
                "category_id" => "01",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "‼️OPEN PRE ORDER 11-15 JULI 2022‼️ Pengen gamisan tapi takut keliatan terlalu formal? Atau.. mau beli gamis tapi takut cuma ngegantung di lemari aja karena gamis identiknya cuma dipake pas jum’atan aja? Tenang aja kang bro, kan ada Salman Series by Muslim Basic😎 Solusi buat kang bro yang mau pake gamis tapi masih tetep mau keliatan CASUAL dan NYAMAN. Tentunya bisa dipake di segala aktivitas Insyā Allāh👍🏻",
                "image" => "salman-seris-02-01-01-01.jpg",
                "price" => 200000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "THOBE SACHET",
                "slug" => "thobe-sachet",
                "product_id" => "03",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "!!OPEN PRE ORDER 26-29 JULI 2022!!Mau pakai thobe premium, tapi biasanya harganya mahal?Tenang aja kang bro, kan ada Adam series by Muslim Basic. Muslim Basic bi'idznillah hadir untuk memfasilitasi kang bro semua supaya bisa TETAP TAAT dan MENAWAN tapi gak bikin kantong jebol",
                "image" => "thobe-sachet-03-01-05-01.jpg",
                "price" => 250000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "NOOR ABAY",
                "slug" => "noor-abay",
                "product_id" => "04",
                "category_id" => "01",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "noor-abay-04-01-01-01.jpg",
                "price" => 160000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "BALQIS ABAYA",
                "slug" => "balqis-abaya",
                "product_id" => "05",
                "category_id" => "01",
                "color_id" => "03",
                "size_id" => "01",
                "description" => "",
                "image" => "balqis-abaya-05-01-03-01.jpg",
                "price" => 160000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "NONA ABAYA",
                "slug" => "nona-abaya",
                "product_id" => "06",
                "category_id" => "01",
                "color_id" => "09",
                "size_id" => "01",
                "description" => "",
                "image" => "nona-abaya-06-01-09-01.jpg",
                "price" => 160000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "jobb",
                "slug" => "jobb",
                "product_id" => "07",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "jobb-07-01-05-01.jpg",
                "price" => 200000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "SALT N PEPPER",
                "slug" => "salt-n-pepper",
                "product_id" => "08",
                "category_id" => "01",
                "color_id" => "012",
                "size_id" => "01",
                "description" => "",
                "image" => "salt-n-pepper-08-01-012-01.jpg",
                "price" => 200000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "ARJUNA WEDA",
                "slug" => "arjuna-weda",
                "product_id" => "09",
                "category_id" => "01",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "arjuna-weda-09-01-06-01.jpg",
                "price" => 200000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "LOIS JEANS",
                "slug" => "lois-jeans",
                "product_id" => "10",
                "category_id" => "01",
                "color_id" => "05",
                "size_id" => "01",
                "description" => "",
                "image" => "lois-jeans-10-01-05-01.jpg",
                "price" => 250000,
                "weight" => 5000,
                "stock" => 100,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris",
                "product_id" => "01",
                "category_id" => "04",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-01-04-01-01.jpg",
                "price" => 160000,
                "weight" => 4000,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris",
                "product_id" => "02",
                "category_id" => "04",
                "color_id" => "07",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-02-04-07-01.jpg",
                "price" => 175000,
                "weight" => 4000,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris",
                "product_id" => "03",
                "category_id" => "04",
                "color_id" => "08",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-03-04-08-01.jpg",
                "price" => 160000,
                "weight" => 4000,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris",
                "product_id" => "04",
                "category_id" => "04",
                "color_id" => "01",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-04-04-01-01.jpg",
                "price" => 160000,
                "weight" => 4000,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ],
            [
                "name" => "HIJAB SERIS",
                "slug" => "hijab-seris",
                "product_id" => "05",
                "category_id" => "04",
                "color_id" => "06",
                "size_id" => "01",
                "description" => "",
                "image" => "hijab-seris-05-04-06-01.jpg",
                "price" => 160000,
                "weight" => 4000,
                "stock" => 50,
                "is_valid" => 1,
                "created_at" => TIme::now()
            ]
        ];

        // Using Query Builder
        $this->db->table('m_product')->insertBatch($data);
    }
}
